# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: kontakt 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "kontakt".freeze
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Olga Velina".freeze]
  s.date = "2020-09-30"
  s.email = "ahmadeeva.ou@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "init.rb",
    "install",
    "kontakt.gemspec",
    "lib/kontakt.rb",
    "lib/kontakt/api.rb",
    "lib/kontakt/config.rb",
    "lib/kontakt/engine.rb",
    "lib/kontakt/middleware.rb",
    "lib/kontakt/rails/controller.rb",
    "lib/kontakt/rails/controller/redirects.rb",
    "lib/kontakt/rails/controller/url_rewriting.rb",
    "lib/kontakt/rails/helpers.rb",
    "lib/kontakt/rails/helpers/javascript_helper.rb",
    "lib/kontakt/rails/helpers/url_helper.rb",
    "lib/kontakt/user.rb"
  ]
  s.homepage = "http://github.com/heyjimmy/kontakt".freeze
  s.rubygems_version = "3.1.2".freeze
  s.summary = "Vkontakte api for Rails applications".freeze
end

